<p><a href="#section">jump to section with <code>href="#section"</code></a> (doesn't work)</p>

<p><a href="#/#section">jump to section with full path specified <code>href="#/#section"</code></a> (works, but don't <a href="https://github.com/sveltejs/kit/issues/13318">refresh in Safari</a> if also using <code>output.bundleStrategy === 'inline'</code>)</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<h1 id="section">Section heading</h1>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam dignissimos modi omnis expedita cum repellendus voluptatibus? Laudantium optio accusamus, praesentium eum quas vel assumenda nobis sed aliquam, facilis dolore alias. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae deserunt culpa alias! Mollitia laborum voluptate corporis provident similique ipsum vitae, facere, nobis consectetur tempore, dicta iure beatae harum maxime? Alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo incidunt eos aut in suscipit quam a eveniet, molestias, soluta quaerat dicta doloremque ducimus accusamus mollitia aliquid similique temporibus quos fuga? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora perspiciatis laboriosam veniam amet ex praesentium itaque tenetur ipsum cupiditate ullam assumenda provident soluta voluptatibus dolorum, sit dolores sequi porro. Nostrum?</p>